image:
  name: hashicorp/terraform:0.12.20
  entrypoint:
    - '/usr/bin/env'
    - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'

stages:
  - test
  - deploy
  - remove

validate:
  stage: test
  script:
    - chmod +x .ci-scripts/validate.sh
    - ./.ci-scripts/validate.sh /builds/${PROJECT_PATH}/bundles

apply:
  stage: deploy
  script:
    - chmod +x .ci-scripts/apply.sh
    - ./.ci-scripts/apply.sh $CI_MERGE_REQUEST_TARGET_BRANCH_NAME /builds/${PROJECT_PATH}/bundles
  only:
    - merge_request
  except:
    variables:
      - $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "trash"


destroy:
  stage: remove
  script:
    - chmod +x .ci-scripts/destroy.sh
    - ./.ci-scripts/destroy.sh /builds/${PROJECT_PATH}/bundles
  only:
    - trash