name: cicd
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: verify-terraform
      run: terraform --version
    - name: validate
      run:
        .ci-scripts/validate.sh bundles
