name: cicd
on: [push]
jobs:
    deploy:
      runs-on: ubuntu-latest
      steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Load Variables
        id: load_envvars
        env:
          TF_VAR_AWS_ACCOUNT: ${{ secrets.TF_VAR_AWS_ACCOUNT }}
          TF_VAR_aws_region: ${{ secrets.TF_VAR_AWS_REGION }}
          TF_VAR_bucket_tfstate_name: ${{ secrets.TF_VAR_BUCKET_TFSTATE_NAME }}
          TF_VAR_dynamodb_tfstate_table: ${{ secrets.TF_VAR_DYNAMODB_TFSTATE_TABLE }}
          TF_VAR_PROJECT_NAME: ${{ secrets.TF_VAR_PROJECT_NAME }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          echo ${GITHUB_REF##*/}
          export TARGET_BRANCH=${GITHUB_REF##*/}
      - name: Validate Terraform
        id: validate_tf
        run: |
          chmod +x .ci-scripts/validate.sh
          echo "::workflow-command::.ci-scripts/validate.sh bundles"
      - name: Deploy
        id: deploy
        if: github.ref == 'refs/heads/staging' || github.ref == 'refs/heads/master'
        run: |
          chmod +x ./.ci-scripts/apply.sh
          ./.ci-scripts/apply.sh $TARGET_BRANCH bundles
      - name: Destroy
        id: destroy
        if: github.ref == 'refs/heads/trash'
        run: |
          chmod +x ./.ci-scripts/destroy.sh
          ./.ci-scripts/destroy.sh bundles